In [ ]:
import pandas as pd

---
## ***DataFrame - Test***
---

In [2]:
df_test = pd.read_csv('../data/test.csv')

---
## ***DataFrame - Train***
---

In [ ]:
df_train = pd.read_csv('../data/train.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

---
## ***VARIABLE - FAMILIARES***
---

In [4]:
df_test['Familiares'] = df_test['SibSp'] + df_test['Parch']
df_train['Familiares'] = df_train['SibSp'] + df_train['Parch']

---
## ***VARIBALE - SOURCE***
---

In [6]:
df_test['Source'] = 'Test'
df_train['Source'] = 'Train'

In [7]:
# Como df_test no tiene la columna 'Survived' la agregamos como None
df_test['Survived'] = None

In [8]:
df_junto = pd.concat([df_test, df_train], ignore_index=True)
print('========= DataFarme conjunto =========')
display(df_junto)

========= DataFarme conjunto =========

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familiares,Source,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Test,None
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Test,None
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Test,None
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Test,None
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Test,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,Train,0
1305,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,Train,1
1306,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,Train,0
1307,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,Train,1
1308,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,Train,0

#

---
### ***Edad promedio***
---

In [9]:
edad_prom = df_junto['Age'].mean()
print(f'Edad Promedio de todo el dataset: {int(edad_prom.round())} años')

Edad Promedio de todo el dataset: 30 años

---
### ***Supervivenvia***
---

In [10]:
#Solo usamos train porque test no tiene Survived
sobrevivientes = df_train[df_train['Survived'] == 1].shape[0]
muertos = df_train[df_train['Survived'] == 0].shape[0]

print(f"Sobrevivieron: {sobrevivientes} pasajeros")
print(f"Murieron: {muertos} pasajeros")

Sobrevivieron: 342 pasajeros
Murieron: 549 pasajeros

---
### ***Tarifa promedio - Primera clase***
---

In [11]:
primera_class = df_junto[df_junto['Pclass'] == 1]['Fare'].mean()
print(f'Tarifa promedio en primera clase: {primera_class.round(2)} dolares')

Tarifa promedio en primera clase: 87.51 dolares

---
### ***Viaje con un familiar***
---

In [ ]:
# Sin familiares:
sin_familiares = df_junto[df_junto['Familiares'] == 0]
print(f'Numero de pasajeros sin familiares: {len(sin_familiares)}')

Numero de pasajeros sin familiares: 790

In [ ]:
# Un solo familiar:
familiar_unico = df_junto[df_junto['Familiares'] == 1]
print(f'Personas que viajaron solo con UN familiar: {len(familiar_unico)}')

Personas que viajaron solo con UN familiar: 235

In [ ]:
# Más de un familiar:
familiar_varios = df_junto[df_junto['Familiares'] > 1]
print(f'Personas que viajaron con MÁS DE UN familiar: {len(familiar_varios)}')

Personas que viajaron con MÁS DE UN familiar: 284

---
### ***Edad más joven y más vieja***
---

In [13]:
edad_min = df_junto['Age'].min()
edad_max = df_junto['Age'].max()

print(f"Pasajero más joven: {edad_min} años")
print(f"Pasajero más viejo: {edad_max} años")

Pasajero más joven: 0.17 años
Pasajero más viejo: 80.0 años

---
### ***Pasajeros por lugar de embarque***
---

In [20]:
print(df_junto['Embarked'].value_counts())
print("\n===== Porcentaje =====\n")
s = df_junto['Embarked'].value_counts()
total = len(df_junto)
print(f"Southampton (S): {round(s['S']/total*100, 1)}%")
print(f"Cherbourg   (C): {round(s['C']/total*100, 1)}%")
print(f"Queenstown  (Q): {round(s['Q']/total*100, 1)}%")

Embarked
S    914
C    270
Q    123
Name: count, dtype: int64

===== Porcentaje =====

Southampton (S): 69.8%
Cherbourg   (C): 20.6%
Queenstown  (Q): 9.4%

---
### ***Preguntas adicionales y proporción***
---

In [21]:
# Conteo
print("=== Conteo ===")
print(df_train.groupby('Sex')['Survived'].sum())

# Proporcionalmente
print("\n=== Proporción ===")
print(df_train.groupby('Sex')['Survived'].mean().round(2))

=== Conteo ===
Sex
female    233
male      109
Name: Survived, dtype: int64

=== Proporción ===
Sex
female    0.74
male      0.19
Name: Survived, dtype: float64

In [25]:
ninos = df_train[df_train['Age'] < 18]
hombres_adultos = df_train[(df_train['Age'] >= 18) & (df_train['Sex'] == 'male')]

print("=== Conteo ===")
print(f"Niños sobrevivieron: {ninos['Survived'].sum()}")
print(f"Hombres adultos sobrevivieron: {hombres_adultos['Survived'].sum()}")

print("\n=== Proporción ===")
print(f"Tasa niños: {round(ninos['Survived'].mean()*100, 1)}%")
print(f"Tasa hombres adultos: {round(hombres_adultos['Survived'].mean()*100, 1)}%")

=== Conteo ===
Niños sobrevivieron: 61
Hombres adultos sobrevivieron: 70

=== Proporción ===
Tasa niños: 54.0%
Tasa hombres adultos: 17.7%

In [26]:
mayores_50 = df_train[df_train['Age'] > 50]
menores_10 = df_train[df_train['Age'] < 10]
otros = df_train[(df_train['Age'] >= 10) & (df_train['Age'] <= 50)]

# Conteo
print("=== Conteo ===")
print(f"Mayores de 50 sobrevivieron: {mayores_50['Survived'].sum()}")
print(f"Menores de 10 sobrevivieron: {menores_10['Survived'].sum()}")
print(f"Otros sobrevivieron: {otros['Survived'].sum()}")

# Proporcionalmente
print("\n=== Proporción ===")
print(f"Tasa mayores de 50: {round(mayores_50['Survived'].mean()*100, 1)}%")
print(f"Tasa menores de 10: {round(menores_10['Survived'].mean()*100, 1)}%")
print(f"Tasa otros: {round(otros['Survived'].mean()*100, 1)}%")

=== Conteo ===
Mayores de 50 sobrevivieron: 22
Menores de 10 sobrevivieron: 38
Otros sobrevivieron: 230

=== Proporción ===
Tasa mayores de 50: 34.4%
Tasa menores de 10: 61.3%
Tasa otros: 39.1%

In [27]:
# Conteo
print("=== Conteo ===")
print(df_train.groupby('Embarked')['Survived'].sum())

# Proporcionalmente
print("\n=== Proporción ===")
print((df_train.groupby('Embarked')['Survived'].mean()*100).round(1))

=== Conteo ===
Embarked
C     93
Q     30
S    217
Name: Survived, dtype: int64

=== Proporción ===
Embarked
C    55.4
Q    39.0
S    33.7
Name: Survived, dtype: float64

In [33]:
#que relación hay en el puerto C por alto indice de supervivencia?
tabla = pd.crosstab(df_train['Embarked'], df_train['Pclass'], normalize='index').mul(100).round(1)
print(tabla)

Pclass       1     2     3
Embarked
C         50.6  10.1  39.3
Q          2.6   3.9  93.5
S         19.7  25.5  54.8

In [28]:
# Conteo
print("=== Conteo ===")
print(df_train.groupby('Pclass')['Survived'].sum())

# Proporcionalmente
print("\n=== Proporción ===")
print((df_train.groupby('Pclass')['Survived'].mean()*100).round(1))

=== Conteo ===
Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

=== Proporción ===
Pclass
1    63.0
2    47.3
3    24.2
Name: Survived, dtype: float64