# ***ANÁLISIS ESTADÍSTICO 2***

In [96]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

---
## ***DataFrame - Test***
---

In [97]:
df_test = pd.read_csv('../data/test.csv')

---
## ***DataFrame - Train***
---

In [98]:
df_train = pd.read_csv('../data/train.csv')
display(df_train)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

---
## ***Variable Familiares***
---

In [99]:
df_test['Familiares'] = df_test['SibSp'] + df_test['Parch']
df_train['Familiares'] = df_train['SibSp'] + df_train['Parch']

---
## ***Copias de seguridad de los DataFrames originales***
---

In [100]:
# Estos no se tocan más
train_original = df_train.copy()
test_original = df_test.copy()

In [101]:
df_test['Source'] = 'Test'
df_train['Source'] = 'Train'

In [102]:
# Como df_test no tiene la columna 'Survived' la agregamos como None
df_test['Survived'] = None

In [103]:
df_junto = pd.concat([df_test, df_train], ignore_index=True)
print('========= DataFarme conjunto =========')
display(df_junto)

========= DataFarme conjunto =========

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familiares,Source,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Test,None
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Test,None
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Test,None
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Test,None
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Test,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,Train,0
1305,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,Train,1
1306,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,Train,0
1307,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,Train,1
1308,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,Train,0

#

---
### ***Edad promedio***
---

In [104]:
edad_prom = df_junto['Age'].mean()
print(f'Edad Promedio de todo el dataset: {int(edad_prom.round())} años')

Edad Promedio de todo el dataset: 30 años

---
### ***Supervivenvia***
---

In [105]:
vivos = df_train['Survived'].sum()
print(f'Total de personas vivas: {vivos} personas')
print(f'Total de personas fallecidas: {len(df_train) - vivos} personas')

Total de personas vivas: 342 personas
Total de personas fallecidas: 549 personas

---
### ***Tarifa promedio - Primera clase***
---

In [106]:
primera_class = df_junto[df_junto['Pclass'] == 1]['Fare'].mean()
#print(f'Tarifa promedio en primera clase: {primera_class['Fare'].mean()}')
print(f'Tarifa promedio en primera clase: {primera_class.round(2)} dolares')

Tarifa promedio en primera clase: 87.51 dolares

---
### ***Viaje con un familiar***
---

In [ ]:
# Un solo familiar:
familiar_unico = df_junto[df_junto['Familiares'] == 1]
print(f'Personas que viajaron solo con UN familiar: {len(familiar_unico)}')

Personas que viajaron solo con UN familiar: 235

In [ ]:
# Más de un familiar:
familiar_varios = df_junto[df_junto['Familiares'] > 1]
print(f'Personas que viajaron con MÁS DE UN familiar: {len(familiar_varios)}')

Personas que viajaron con MÁS DE UN familiar: 284