# ***PROYECTO TITANIC - ANÁLISIS CON PANDAS***

In [57]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

---
## ***DataFrame - Test***
---

In [58]:
df_test = pd.read_csv('../data/test.csv')
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

---
## ***DataFrame - Train***
---

In [59]:
df_train = pd.read_csv('../data/train.csv')
df_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

---
## ***Descripción de DataSets***
---

In [60]:
print('========= Variables - Test =========')
display(df_test.dtypes)

========= Variables - Test =========

PassengerId      int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [61]:
print('========= Variables - Train =========')
display(df_train.dtypes)

========= Variables - Train =========

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

---
## ***Comparaciones y estadísticas básicas de los DataFrames***
---

In [62]:
print('========= Estadisticas - Test =========')
display(df_test.describe())

========= Estadisticas - Test =========

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [63]:
print('========= Estadisticas - Train =========')
display(df_train.describe())

========= Estadisticas - Train =========

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

---
# ***Variable - Familiares***
---

In [64]:
df_test['Familiares'] = df_test['SibSp'] + df_test['Parch']
df_train['Familiares'] = df_train['SibSp'] + df_train['Parch']

print(df_train['Familiares'].describe())

count    891.000000
mean       0.904602
std        1.613459
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max       10.000000
Name: Familiares, dtype: float64

---
## ***Copias de seguridad de los DataFrames originales***
---

In [65]:
# Estos no se tocan más
train_original = df_train.copy()
test_original = df_test.copy()

In [66]:
df_test['Source'] = 'Test'
df_train['Source'] = 'Train'

In [67]:
# Como df_test no tiene la columna 'Survived' la agregamos como None
df_test['Survived'] = None

In [68]:
df_junto = pd.concat([df_test, df_train], ignore_index=True)
print('========= DataFarme conjunto =========')
display(df_junto.head())

========= DataFarme conjunto =========

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familiares,Source,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Test,None
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Test,None
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Test,None
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Test,None
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Test,None

---
## ***Estadísticas conjuntas y representación***
---

In [69]:
display(df_junto.describe())

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Familiares
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,655.000000,2.294882,29.881138,0.498854,0.385027,33.295479,0.883881
std,378.020061,0.837836,14.413493,1.041658,0.865560,51.758668,1.583639
min,1.000000,1.000000,0.170000,0.000000,0.000000,0.000000,0.000000
25%,328.000000,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,655.000000,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,982.000000,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,1309.000000,3.000000,80.000000,8.000000,9.000000,512.329200,10.000000

### ***Tamaños y proporción***

In [77]:
print(f'Filas de train: {len(df_train)}')
print(f'Filas de test: {len(df_test)}')
print(f'Total de filas (con el df_junto): {len(df_junto)}')
p_test = round(len(df_test)/len(df_junto)*100)
print(f'Proporción de datos de test: {p_test}%')
p_train = round(len(df_train)/len(df_junto)*100)
print(f'Proporción de datos train: {p_train}%')

Filas de train: 891
Filas de test: 418
Total de filas (con el df_junto): 1309
Proporción de datos de test: 32%
Proporción de datos train: 68%

### ***Variables importantes (análisis de proporción)***

In [80]:
variables = ['Age', 'Fare', 'Pclass'] #Sirven para clasificar mejor

for var in variables:
    print(f'========= {var} =========')
    print(f'df_test: {round(df_test[var].mean())}')
    print(f'df_train: {round(df_train[var].mean())}')

========= Age =========
df_test: 30
df_train: 30
========= Fare =========
df_test: 36
df_train: 32
========= Pclass =========
df_test: 2
df_train: 2