# ***VARIABLES NUEVAS Y FALTANTES***

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

---
## ***DataFrame - Test***
---

In [2]:
df_test = pd.read_csv('../data/test.csv')

---
## ***DataFrame - Train***
---

In [3]:
df_train = pd.read_csv('../data/train.csv')

---
# ***Variable - Familiares***
---

In [4]:
df_test['Familiares'] = df_test['SibSp'] + df_test['Parch']
df_train['Familiares'] = df_train['SibSp'] + df_train['Parch']

print(df_train['Familiares'].describe())

count    891.000000
mean       0.904602
std        1.613459
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max       10.000000
Name: Familiares, dtype: float64

---
## ***Copias de seguridad de los DataFrames originales***
---

In [5]:
# Estos no se tocan más
train_original = df_train.copy()
test_original = df_test.copy()

In [6]:
df_test['Source'] = 'Test'
df_train['Source'] = 'Train'

In [7]:
# Como df_test no tiene la columna 'Survived' la agregamos como None
df_test['Survived'] = None

In [8]:
df_junto = pd.concat([df_test, df_train], ignore_index=True)
print('========= DataFarme conjunto =========')
display(df_junto.head())

========= DataFarme conjunto =========

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Familiares,Source,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,Test,None
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1,Test,None
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,Test,None
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,Test,None
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2,Test,None

---
## ***Estadísticas conjuntas y representación***
---

In [9]:
display(df_junto.describe())

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Familiares
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,655.000000,2.294882,29.881138,0.498854,0.385027,33.295479,0.883881
std,378.020061,0.837836,14.413493,1.041658,0.865560,51.758668,1.583639
min,1.000000,1.000000,0.170000,0.000000,0.000000,0.000000,0.000000
25%,328.000000,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,655.000000,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,982.000000,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,1309.000000,3.000000,80.000000,8.000000,9.000000,512.329200,10.000000

### ***Tamaños y proporción***

In [ ]:
print(f'Filas de train: {len(df_train)}')
print(f'Filas de test: {len(df_test)}')
print(f'Total de filas (con el df_junto): {len(df_junto)}')
p_test = round(len(df_test)/len(df_junto)*100)
print(f'Proporción de datos de test: {p_test}%')
p_train = round(len(df_train)/len(df_junto)*100)
print(f'Proporción de datos train: {p_train}%')

Filas de train: 891
Filas de test: 418
Total de filas (con el df_junto): 1309
Proporción de datos de test: 32%
Proporción de datos train: 68%

### ***Variables importantes (análisis de proporción)***

In [11]:
variables = ['Age', 'Fare', 'Pclass'] #Sirven para clasificar mejor

for var in variables:
    print(f'========= {var} =========')
    print(f'df_test: {round(df_test[var].mean())}')
    print(f'df_train: {round(df_train[var].mean())}')

========= Age =========
df_test: 30
df_train: 30
========= Fare =========
df_test: 36
df_train: 32
========= Pclass =========
df_test: 2
df_train: 2

---
## ***Datos faltantes en variables***
---

In [45]:
# .isnul() busca en cada varibale del df los espacios nulos, devuelve True o False
# .sum() suma el total de espacios nulos en esa variable, True = 1, False = 0
nulos_test = df_test.isnull().sum()
print(f'===== Datos faltantes en Test ======\n')
print(nulos_test)
print(f'\n===== Total: {nulos_test.sum()} =====')

===== Datos faltantes en Test ======

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Familiares       0
Source           0
Survived       418
dtype: int64

===== Total: 832 =====

In [46]:
nulos_train = df_train.isnull().sum()
print(f'===== Datos faltantes en Train ======\n')
print(nulos_train)
print(f'\n===== Total: {nulos_train.sum()} =====')

===== Datos faltantes en Train ======

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Familiares       0
Source           0
dtype: int64

===== Total: 866 =====

In [47]:
nulos_total = df_junto.isnull().sum()
print(f'===== Datos faltantes en Total ======\n')
print(nulos_total)
print(f'\n===== Total: {nulos_total.sum()} =====')

===== Datos faltantes en Total ======

PassengerId       0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
Familiares        0
Source            0
Survived        418
dtype: int64

===== Total: 1698 =====

In [56]:
p_nulos = round((df_junto.isnull().sum()/ len(df_junto)) *100)
total = round((nulos_total.sum()/len(df_junto)) *100)
print(f'===== Porcentaje de datos faltantes totales =====\n')
print(p_nulos)
print(f'\n ===== Porcentaje total: {total} =====')

===== Porcentaje de datos faltantes totales =====

PassengerId     0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            20.0
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.0
Cabin          77.0
Embarked        0.0
Familiares      0.0
Source          0.0
Survived       32.0
dtype: float64

 ===== Porcentaje total: 130 =====